baseurl = "https://azema.tech/"
languageCode = "en-us"
Title = "Baptiste Azéma"
theme = "hugo_theme_pickles"  
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright Azéma"
#custom_css = "/static/css/custom.css"

[params]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "AzemaBaptiste"
  linkedin = "baptiste-azema-6a94b44a"
  # Google Analytics API key.
  ga_api_key = "UA-156741236-1"
  author = "Baptiste Azéma"
  authorwebsite = "azema.tech"
  avatar = "/static/img/logo.png"
  contact = "mailto:baptiste@azema.tech"
  #bio = "Your short bio"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Curriculum Vitae"
  # Logo image. This is displayed ogp image.
  logo = "/static/img/logo.png"
  favicon = "/static/img/logo.png"


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
