baseurl = "https://azema.tech/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Baptiste Azéma"

theme = "gokarna"

custom_css = "/css/custom.css"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/img/logo.png"
#  avatarURL = "/img/logo.jpg"


  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  description = "I’m just a simple man, trying to make my way in the universe."

  customHeadHTML= '''
  <link rel="stylesheet" type="text/css" href="/css/custom.css">
  <script async defer data-website-id="20d692ae-70d7-4393-9099-1661a68926d5" src="https://metrics.boris.sh/umami.js"></script>
  '''
