name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: git submodule init && git submodule update
    - name: build hugo
      uses: srt32/hugo-action@master
      args: ["--themesDir themes"]
    - name: ftp deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.cluster029.hosting.ovh.net
        FTP_USERNAME: azemateciv
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: public
        REMOTE_DIR: www
        ARGS: --delete --transfer-all
