name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sudo apt-get install hugo && hugo --gc --themesDir themes
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.cluster029.hosting.ovh.net
        FTP_USERNAME: azemateciv
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: public
        REMOTE_DIR: www
        ARGS: --delete --transfer-all --no-empty-dirs
